CREATE TABLE tbl_Saved_Projects (
  SP_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  SP_name VARCHAR,
  SP_description VARCHAR,
  SP_user_ID INT,
  SP_approach INT,
  SP_direct_discount_rate NUMERIC,
  SP_beta NUMERIC,
  SP_riskless_rate NUMERIC,
  SP_market_risk_premium NUMERIC,
  SP_debt_ratio NUMERIC,
  SP_cost_of_borrowing NUMERIC,
  SP_working_capital_initial_investment NUMERIC,
  SP_working_capital_percentage NUMERIC,
  SP_salvageable_fraction NUMERIC,
  SP_tax_rate NUMERIC,
  SP_initial_investment NUMERIC,
  SP_opportunity_cost NUMERIC,
  SP_lifetime INT,
  SP_salvage_value NUMERIC,
  SP_Depreciation_Method_ID INT,
  SP_tax_credit NUMERIC,
  SP_other_invest INT,
  SP_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  SP_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tbl_Other_Factors (
  OF_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  OF_Saved_Projects_ID INT REFERENCES tbl_Saved_Projects(SP_ID) ON DELETE CASCADE,
  OF_type INT,
  OF_label TEXT,
  OF_value NUMERIC,
  OF_default_growth_rate NUMERIC
);

CREATE TABLE tbl_Growth_Years (
  GY_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  GY_Other_Factors_ID INT REFERENCES tbl_Other_Factors(OF_ID) ON DELETE CASCADE,
  GY_year INT,
  GY_growth_rate NUMERIC
);
